---
sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - pipenv run flake8 test
  - sleep 30
  - pipenv run pytest test -v
