version: "3"
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      TZ:
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    build: ./logstash
    container_name: logstash
    environment:
      TZ:
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ${HOME}:/home
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      TZ:
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
